services:
  frontend:
    build:
      context: ../../cmd/frontend/nextjs
      dockerfile: ../../../build/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WEBSOCKET_PROTOCOL=ws
      - WEBSOCKET_PORT=8081
  webserver:
    build:
      context: ../../
      dockerfile: build/webserver/Dockerfile
    ports:
      - "8081:80"
    environment:
      - WEBSOCKET_PORT=80